/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/models/controlbox/base_basic_shaded.glb components/models/ControlBoxShader.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/base_basic_shaded.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </group>
  )
}

useGLTF.preload('/base_basic_shaded.glb')
