/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/models/datacenter/green-eye.glb -o components/models/GreenEye.jsx 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import Colors from '@/utils/color';

export function GreenEye(props: any) {
   const { nodes, materials } = useGLTF('/3d/models/datacenter/green-eye.glb');
   return (
      <group {...props} dispose={null}>
         <mesh geometry={(nodes.geometry_0 as any).geometry} material={(nodes.geometry_0 as any).material} />
      </group>
   );
}

useGLTF.preload('/3d/models/datacenter/green-eye.glb');
