/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d/models/spaceship-1.glb -o components/models/SpaceShipOne.jsx 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function SpaceShipOne(props: any) {
   const { nodes } = useGLTF('/3d/models/spaceship-1.glb');
   return (
      <group {...props} dispose={null}>
         <mesh geometry={(nodes.geometry_0 as any).geometry} material={(nodes.geometry_0 as any).material} castShadow={!!props.castShadow} />
      </group>
   );
}

useGLTF.preload('/3d/models/spaceship-1.glb');
